### PR TITLE
Added NextJS Landing Page using Tailwind Starter Kit

### PR DESCRIPTION
**Pull request by MeridjaNassim**
Hello I created a NextJS version of Landing Page using the Tailwind Starter Kit, i also included the necessary configuration for it to work seamlessly here is some of what is included:

1. Tailwind CSS with tailwind.config.css
2. next-images package for handling images imports/requires in server-side
3. PostCSS:  purgecss for removing unused CSS and postcss-preset-env for creating compatible CSS with all browsers
4. Typescript 4 support
5. Scripts: build ssr & build static.

Am contributing to this project mainly because I find it very useful and am thankful for the initiative and secondly as a contribution to Open-Source during Hacktoberfest 2020.

### CODE REVIEW

**Comment by EINazare** [comment]
Hey there, @MeridjaNassim ,

Could you please also add the Page inside our Landing Pages area from our README? https://github.com/creativetimofficial/tailwind-starter-kit#free-design-system-ui-kit

Best,
Manu

**Comment by MeridjaNassim** [comment]
Hello @EINazare, 
I have added it to the readme, but I think that for the link to work it should be added to the master branch. correct me if am wrong. 
Best regards

**Review by EINazare — APPROVED** [review]

**Comment by EINazare** [comment]
Yes, you are correct.
It is done. I've just added your PR.

**Comment by MeridjaNassim** [comment]
Thank you so much

**Comment by MeridjaNassim** [comment]
Thank you so much

**Pull request merged**
